/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package sqlxmap.ui;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import sqlxmap.DatabaseInfo;
import sqlxmap.LayerData;
import sqlxmap.Settings;
import sqlxmap.Tietokantayhteys;

/**
 *
 * @author jgsavola
 */
public class Kyselyikkuna extends javax.swing.JFrame {
    private MapPanel mapPanel;
    private Settings settings;
    
    /**
     * Creates new form Kyselyikkuna
     */
    public Kyselyikkuna(MapPanel mapPanel, Settings settings) {
        initComponents();
        this.mapPanel = mapPanel;
        this.settings = settings;
    }

    public Kyselyikkuna() {
        initComponents();
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        suoritaButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        kyselyEditorPane = new javax.swing.JEditorPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        suoritaButton.setText("Suorita");
        suoritaButton.setFocusable(false);
        suoritaButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        suoritaButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        suoritaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suoritaButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(suoritaButton);

        jScrollPane1.setViewportView(kyselyEditorPane);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void suoritaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suoritaButtonActionPerformed
        String kysely = kyselyEditorPane.getText();
        System.out.println("kysely: " + kysely);
        
        /**
         * Hae ensimmäisen tietokantayhteyden tiedot.
         * 
         * FIXME: listan palauttaminen tuntuu huonolta käyttöliittymältä.
         */
        DatabaseInfo dbinfo = settings.getDbInfo().get(0);
        Tietokantayhteys yhteys = new Tietokantayhteys(dbinfo);
        try {
            yhteys.yhdista();

            LayerData kyselyData = yhteys.teeKysely(kysely);
            mapPanel.addLayerData(kyselyData);
            mapPanel.repaint();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(SQLxMapApp.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(SQLxMapApp.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_suoritaButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kyselyikkuna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kyselyikkuna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kyselyikkuna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kyselyikkuna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Kyselyikkuna().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JEditorPane kyselyEditorPane;
    private javax.swing.JButton suoritaButton;
    // End of variables declaration//GEN-END:variables
}
