all: pdf

pdf: aiheenKuvausJaRakenne.pdf testausdokumentti.pdf käyttöohjeet.pdf

aiheenKuvausJaRakenne.pdf: aiheenKuvausJaRakenne.rst
	rst2pdf $<

testausdokumentti.pdf: testausdokumentti.rst
	rst2pdf $<

käyttöohjeet.pdf: käyttöohjeet.rst
	rst2pdf $<
